<?php
/**
 * Top menu for store
 *
 * @var $this RedLightBlinking_MegaMenu_Block_Page_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('dropdown', 'dropdown-menu') ?>
<?php if($_menu): ?>
	<div class="navbar navbar-inverse navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<div class="visible-xs">
					<div class="form-search-xs"><?php echo $this->getChildHtml('topMenuSearch') ?></div>
				</div>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav mega-menu navbar-nav">
                    <li><a href="/">Home</a></li>
					<?php echo $_menu ?>
					<li><a href="/wishlist/">Wish list</a></li>
					<li><a href="/customer/account/">Account</a></li>
				</ul>
				<div class="social_buttons">
					<span class="social-icon-bar instagram" target="_BLANK"><a href="http://www.http://instagram.com/"></a></span>
					<span class="social-icon-bar twitter" target="_BLANK"><a href="https://twitter.com/"></a></span>
					<span class="social-icon-bar facebook" target="_BLANK"><a href="https://www.facebook.com"></a></span>
					<span class="social-icon-bar google" target="_BLANK"><a href="https://plus.google.com"></a></span>
					<span class="social-icon-bar pinterest" target="_BLANK"><a href="http://www.pinterest.com"></a></span>
				</div>
			</div>
		</div>
	</div>
<?php endif ?>
